spring:
  boot:
    admin:
      client:
        url: http://localhost:9090
        username: admin
        password: changeme
        instance:
          name: demo-backend
          prefer-ip: true
        connect-timeout: 10s
        read-timeout: 10s
        retry-count: 120
        period: 10000
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: 86152
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
